##
##   SQLBans
##
##   For kick and ban messages, use && for the color char,
##     such as &&f for white.
##     Use %reason% for the reason, %admin% for the kicking admin's name
##
##   Track server bans by changing server-name to another name
##
database:
  host: localhost
  port: 3306
  database: sqlbans
  tablename: SQLBans_bans
  auth:
    username: banana
    password: pear
server-name: default
messages:
  command:
    nopermission: '&&cYou do not have permission to use this command'
  disconnect:
    rejected: '&&cVisit our website for unban'
    kicked:
      noreason: '&&cKicked'
      reason: '&&cKicked:&&f %reason%'
    banned:
      noreason: '&&cBanned.'
      reason: '&&cBanned:&&f %reason%'
  ingame:
    kicked:
      normal:
        reason: '&&cKicked %target%: &&f%reason%'
        noreason: '&&cKicked %target%'
      admin:
        reason: '&&c%admin% kicked %target%'
        noreason: '&&c%admin% kicked %target%: &&f%reason%'
    banned:
      normal:
        reason: '&&cBanned %target%: &&f%reason%'
        noreason: '&&cBanned %target%'
      admin:
        reason: '&&c%admin% banned %target%'
        noreason: '&&c%admin% banned %target%: &&f%reason%'
    unbanned:
      normal: '&&cUnbanned %target%'
      admin: '&&c%admin% unbanned %target%'
meow: true