##
##   SQLBans
##
##   Stuff here
##
database:
  host: localhost
  port: 3306
  database: sqlbans
  tablename: SQLBans_bans
  auth:
    username: banana
    password: guava
disconnect:
  banned: Visit our website for unban